#!/bin/bash
# Guide de démarrage rapide

echo "🚀 Guide de démarrage - Threlte 3D + Django + SvelteKit"
echo "========================================================"
echo ""

echo "✅ Prérequis:"
echo "   • Python 3.13+ ✓"
echo "   • Node.js + npm ✓"
echo "   • PostgreSQL (Neon) ✓"
echo ""

echo "📝 Étape 1: Préparation"
echo "   • .env.local créé ✓"
echo "   • backend/settings.py configuré ✓"
echo "   • vercel.json mis à jour ✓"
echo ""

echo "🚀 Étape 2: Lancer le développement local"
echo ""
echo "   Option A - Deux terminaux (manuel):"
echo "   ────────────────────────────────────"
echo ""
echo "   Terminal 1 - Backend Django:"
echo "   $ cd backend"
echo "   $ /home/kd/Bureau/dv-threlte-starter/.venv/bin/python manage.py runserver 0.0.0.0:8000"
echo ""
echo "   Terminal 2 - Frontend SvelteKit:"
echo "   $ npm run dev"
echo "   $ # Ouvrir http://localhost:5173"
echo ""
echo "   Option B - Automatisé (un terminal):"
echo "   ───────────────────────────────────"
echo "   $ chmod +x dev.sh"
echo "   $ ./dev.sh"
echo ""

echo "✅ Étape 3: Vérifier que ça marche"
echo ""
echo "   1. API Django:"
echo "      $ curl http://localhost:8000/api/geometries/"
echo ""
echo "   2. Frontend SvelteKit:"
echo "      $ Ouvrir http://localhost:5173/app"
echo ""
echo "   3. Vous devriez voir vos objets 3D dans la scène!"
echo ""

echo "🌐 Étape 4: Déployer sur Vercel"
echo ""
echo "   1. Ajouter les variables d'environnement au dashboard Vercel:"
echo "      Settings > Environment Variables"
echo ""
echo "      Frontend variables:"
echo "      • PUBLIC_API_URL = https://votre-api-django.vercel.app"
echo "      • PUBLIC_STATIC_URL = https://w0cb58ft2bj7sg0v.public.blob.vercel-storage.com"
echo ""
echo "      Backend variables:"
echo "      • DEBUG = False"
echo "      • SECRET_KEY = votre-clé-de-production"
echo "      • BLOB_READ_WRITE_TOKEN = (token Vercel Blob)"
echo "      • STORE_ID = store_W0CB58Ft2bj7Sg0v"
echo ""
echo "   2. Pousser le code sur GitHub:"
echo "      $ git add -A"
echo "      $ git commit -m 'feat: Django backend + SvelteKit frontend'"
echo "      $ git push origin master"
echo ""
echo "   3. Vercel déploiera automatiquement!"
echo ""

echo "🐛 Dépannage:"
echo ""
echo "   Les objets 3D n'apparaissent pas?"
echo "   ────────────────────────────────"
echo "   • Vérifier: curl http://localhost:8000/api/geometries/"
echo "   • Vérifier le .env.local: PUBLIC_API_URL=http://localhost:8000"
echo "   • Vérifier la console du navigateur (erreurs CORS?)"
echo ""

echo "📚 Fichiers importants:"
echo ""
echo "   • .env.local ................. Config développement local"
echo "   • .env ........................ Config production Vercel"
echo "   • backend/settings.py ........ Configuration Django"
echo "   • vercel.json ................ Configuration déploiement"
echo "   • DEPLOYMENT_GUIDE_COMPLETE.md  Guide détaillé"
echo ""

echo "🎉 C'est bon! Commencez le développement!"
echo ""
