<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/nissan.glb --root /models/ --printwidth 120 --precision 2
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nissan-skyline-gtr-r35-7b142ea3376e4811a326256c59bbc7a2
Title: Nissan Skyline GTR r35
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { createDracoLoader } from '$lib/utils/draco-loader';
	import { Group, LessEqualDepth } from 'three';
	import Bloom from './bloom.svelte';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	import { getCloudinaryAssetUrl } from '$lib/utils/cloudinaryAssets';

	// Runes syntax pour les props, avec un ref par défaut et passage du reste des props
	let { ref = $bindable(new Group()), ...restProps } = $props();

	let gltf = $state<any>(null);

	onMount(() => {
		if (browser) {
			const loadGltf = async () => {
				try {
					return await useGltf(getCloudinaryAssetUrl('nissan2.glb'), {
						dracoLoader: createDracoLoader()
					});
				} catch (e) {
					console.warn('Nissan: Cloudinary fail, trying local...');
					return await useGltf('/models/nissan2.glb', {
						dracoLoader: createDracoLoader()
					});
				}
			};

			loadGltf().then((model: any) => {
				gltf = model;
				function alphaFix(material: any) {
					if (!material) return;
					material.transparent = true;
					material.alphaToCoverage = true;
					material.depthFunc = LessEqualDepth;
					material.depthTest = true;
					material.depthWrite = true;
				}

				model.scene.traverse((child: any) => {
					if (child.isMesh) {
						alphaFix(child.material);
					}
				});
			});
		}
	});
</script>

{#if browser}
	<Bloom />
{/if}

<T is={ref} dispose={false} {...restProps}>
	{#if gltf}
		<T is={gltf.scene} />
	{:else}
		<slot name="fallback" />
	{/if}
</T>
