<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/nissan.glb --root /models/ --printwidth 120 --precision 2
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nissan-skyline-gtr-r35-7b142ea3376e4811a326256c59bbc7a2
Title: Nissan Skyline GTR r35
-->

<script lang="ts">
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { Group, LessEqualDepth } from 'three';
	import Bloom from './bloom.svelte';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	import { getCloudinaryAssetUrl } from '$lib/utils/cloudinaryAssets';

	// Runes syntax pour les props, avec un ref par défaut et passage du reste des props
	let { ref = new Group(), ...restProps } = $props();

	let gltf: any;

	onMount(() => {
		if (browser) {
			gltf = useGltf(getCloudinaryAssetUrl('/models/nissan.glb'));

			gltf?.then((model: any) => {
				function alphaFix(material: any) {
					if (!material) return;
					material.transparent = true;
					material.alphaToCoverage = true;
					material.depthFunc = LessEqualDepth;
					material.depthTest = true;
					material.depthWrite = true;
				}

				model.scene.traverse((child: any) => {
					if (child.isMesh) {
						alphaFix(child.material);
					}
				});
			});
		}
	});
</script>

{#if browser}
	<Bloom />
{/if}

<T is={ref} dispose={false} {...restProps}>
	{#await gltf}
		loading
	{:then gltf}
		<T.Mesh is={gltf.scene} />
	{:catch error}
		<p>Error loading model</p>
	{/await}
</T>
