"""
Django settings for films_backend project.
Generated by 'django-admin startproject' using Django 4.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Chargement des variables d'environnement depuis .env (si le fichier existe)
env_path = Path(__file__).resolve().parent.parent / ".env"
if env_path.exists():
    load_dotenv(env_path)
else:
    # Sur Vercel, les variables viennent du Dashboard, pas de .env
    load_dotenv()  # Charge depuis les variables d'environnement du système

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Vous devrez définir cette variable dans les paramètres de votre projet Vercel
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-g)hz$pnmc@5tnrq43u$2w**+17sk1z#0klovi+bsiykt1779g2"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

# L'URL de production sera ajoutée automatiquement par Vercel.
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "testserver",  # For Django tests
    ".vercel.app",
    ".now.sh",  # For Vercel
    ".railway.app",  # For Railway deployment
    "dv-threlte-starter.vercel.app",
    "dv-threlte-starter-production.up.railway.app",
]

CSRF_TRUSTED_ORIGINS = [
    "https://dv-threlte-starter-production.up.railway.app",
    "https://dv-threlte-starter.vercel.app",
]

# Ajouter dynamiquement l'URL de prévisualisation de Vercel si elle existe
VERCEL_URL = os.environ.get("VERCEL_URL")
if VERCEL_URL and f"https://{VERCEL_URL}" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(f"https://{VERCEL_URL}")

# Ajouter les domaines depuis les variables d'environnement Vercel
VERCEL_URL = os.environ.get("VERCEL_URL")
if VERCEL_URL and VERCEL_URL not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.insert(0, VERCEL_URL)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # Should be before staticfiles
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "storages",  # For S3/B2 storage
    "cloudinary_storage",  # Cloudinary storage (gratuit sans CB)
    "cloudinary",
    "backend.Base_threlte_dv",
    "backend.films",
    "taggit",
]

# Configuration de l'API REST
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    # Personnalisation de l'interface navigable
    "DEFAULT_METADATA_CLASS": "rest_framework.metadata.SimpleMetadata",
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.AcceptHeaderVersioning",
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    # Documentation de l'API
    "DEFAULT_TITLE": "API Films et Géométries",
    "DEFAULT_DESCRIPTION": """
    API de gestion des films et des géométries.

    Endpoints disponibles:
    - /api/films/ : Gestion des films
    - /api/geometries/ : Gestion des géométries
    - /api/types/ : Liste des types disponibles
    - /api/upload/ : Gestion des uploads
    """,
    "SERVE_INCLUDE_SCHEMA": True,
}

# Personnalisation de l'interface d'administration
ADMIN_SITE_HEADER = "Administration du Film Service"
ADMIN_SITE_TITLE = "Film Service Admin"
ADMIN_INDEX_TITLE = "Gestion des Films et Géométries"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "backend.json_response_middleware.JSONResponseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.app"
ASGI_APPLICATION = "backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Configuration pour utiliser SQLite en local et PostgreSQL en production via une URL.
# Si DATABASE_URL est définie (en production sur Railway, Vercel, etc.), on utilise PostgreSQL.
# Sinon, on utilise une base de données SQLite locale pour le développement.
database_url = os.environ.get("DATABASE_URL")
if database_url and database_url.strip():
    DATABASE_URL = database_url

    # Parse l'URL de la base de données
    db_config = dj_database_url.parse(DATABASE_URL)

    # Configuration optimisée pour les services de DB cloud (Neon, Railway, etc.)
    # La plupart exigent SSL.
    db_config["OPTIONS"] = db_config.get("OPTIONS", {})
    db_config["OPTIONS"].update(
        {
            "sslmode": "require",
            "connect_timeout": 10,
        }
    )

    # Réutilisation des connexions pour la performance
    db_config["CONN_MAX_AGE"] = 600
    # ATOMIC_REQUESTS=False est souvent recommandé pour pgbouncer/poolers
    db_config["ATOMIC_REQUESTS"] = False

    DATABASES = {"default": db_config}
else:
    # Configuration pour le développement local (SQLite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "backend" / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files configuration
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Media files configuration
USE_B2_STORAGE = os.environ.get("USE_B2_STORAGE", "False") == "True"
USE_CLOUDINARY = os.environ.get("USE_CLOUDINARY", "False") == "True"

if USE_B2_STORAGE:
    # Backblaze B2 Storage (plus économique que Cloudinary)
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    # Configuration B2 S3-compatible
    AWS_ACCESS_KEY_ID = os.environ.get("B2_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("B2_APPLICATION_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("B2_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.environ.get("B2_ENDPOINT_URL")
    AWS_S3_REGION_NAME = os.environ.get("B2_REGION", "eu-central-003")

    # URL des médias
    MEDIA_URL = (
        f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
        if AWS_S3_ENDPOINT_URL and AWS_STORAGE_BUCKET_NAME
        else "/media/"
    )

    # Configuration supplémentaire pour B2
    AWS_DEFAULT_ACL = None  # B2 ne supporte pas ACL comme S3
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False  # URLs publiques sans signature

elif USE_CLOUDINARY:
    # Cloudinary Storage (100% gratuit, 25GB)
    import cloudinary
    import cloudinary.api
    import cloudinary.uploader

    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
        "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
        "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
    }

    cloudinary.config(
        cloud_name=CLOUDINARY_STORAGE["CLOUD_NAME"],
        api_key=CLOUDINARY_STORAGE["API_KEY"],
        api_secret=CLOUDINARY_STORAGE["API_SECRET"],
        secure=True,
    )

    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

    # URL de base Cloudinary
    MEDIA_URL = f"https://res.cloudinary.com/{CLOUDINARY_STORAGE['CLOUD_NAME']}/"
else:
    # Stockage local (développement)
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Legacy: Configuration Vercel Blob Storage (deprecated)
BLOB_READ_WRITE_TOKEN = os.environ.get("BLOB_READ_WRITE_TOKEN")
VERCEL_BLOB_STORE_ID = os.environ.get("STORE_ID", "your-store-id")

# Correction du warning Django URLField (Django 6.0)
FORMS_URLFIELD_ASSUME_HTTPS = True

# CORS Configuration
CORS_ALLOW_CREDENTIALS = True

# En développement, permettre toutes les origines pour plus de flexibilité
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False

# En production, spécifier les origines autorisées
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:4173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
    "https://dv-threlte-starter.vercel.app",
]

# Autoriser les sous-domaines Vercel (pour les previews)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://dv-threlte-starter-.*\.vercel\.app$",
]

# Ajouter dynamiquement l'URL Railway si elle existe
RAILWAY_PUBLIC_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN")
if (
    RAILWAY_PUBLIC_DOMAIN
    and f"https://{RAILWAY_PUBLIC_DOMAIN}" not in CORS_ALLOWED_ORIGINS
):
    CORS_ALLOWED_ORIGINS.append(f"https://{RAILWAY_PUBLIC_DOMAIN}")

# Ajouter dynamiquement l'URL de prévisualisation de Vercel si elle existe
VERCEL_URL = os.environ.get("VERCEL_URL")
if VERCEL_URL and f"https://{VERCEL_URL}" not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(f"https://{VERCEL_URL}")

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration for Vercel
# NOTE: Vercel Serverless has a READ-ONLY filesystem, so we can ONLY use console handler
# (no file handler possible on Vercel - use stdout/stderr instead)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "Base_threlte_dv": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
