# Generated by Django 5.1.2 on 2025-11-02 16:27

import Base_threlte_dv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='model_type',
            field=models.CharField(blank=True, choices=[('gltf', 'glTF'), ('glb', 'GLB')], help_text='Format du fichier 3D', max_length=10),
        ),
        migrations.AddField(
            model_name='geometry',
            name='model_url',
            field=models.URLField(blank=True, help_text='URL du fichier 3D (glTF/GLB) sur Vercel Blob', max_length=1024),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='name',
            field=models.CharField(blank=True, default='nissan', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='position',
            field=models.JSONField(default=Base_threlte_dv.models.get_default_position),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='rotation',
            field=models.JSONField(default=Base_threlte_dv.models.get_default_rotation),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='type',
            field=models.CharField(choices=[('box', 'Box'), ('torus', 'Torus'), ('icosahedron', 'Icosahedron'), ('nissangame', 'Nissan Game'), ('bibigame', 'Bibi Game'), ('garden', 'Garden'), ('bibi', 'Bibi'), ('vague', 'Vague'), ('sphere', 'Sphere'), ('nissan', 'Nissan'), ('tissus', 'Tissus'), ('desk', 'Desk')], default=Base_threlte_dv.models.Geometry.write_type_py, max_length=20),
        ),
    ]
