# Generated by Django 5.1.2 on 2025-11-05 17:23

from django.db import migrations

def populate_model_urls(apps, schema_editor):
    Geometry = apps.get_model('Base_threlte_dv', 'Geometry')
    for geometry in Geometry.objects.all():
        if geometry.type == 'desk':
            geometry.model_url = '/assets/Desk-bati.glb'
            geometry.model_type = 'glb'
        elif geometry.type == 'garden':
            geometry.model_url = '/static/assets/garden.gltf'
            geometry.model_type = 'gltf'
        # For nissan and bibi, the models are not found in the project.
        # Leaving the model_url blank for now.
        # The user mentioned they are on Vercel Blob.
        # The user will have to manually update these.
        
        # For other types like vague, tissus, sphere, etc.,
        # they are either Svelte components or basic shapes,
        # so they don't have a model_url.
        
        geometry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0002_alter_geometry_options_geometry_model_type_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_model_urls),
    ]