# Generated by Django 5.1.2 on 2025-11-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0003_auto_20251105_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='model_file',
            field=models.FileField(blank=True, help_text='Fichier 3D local (.glb, .gltf)', null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='model_url',
            field=models.URLField(blank=True, help_text='URL du fichier 3D (rempli automatiquement depuis model_file)', max_length=1024),
        ),
    ]
