# Generated by Django 5.1.2 on 2025-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0004_geometry_model_file_alter_geometry_model_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
