# Generated by Django 5.1.2 on 2025-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0005_bloblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(help_text='Cloudinary Public ID', max_length=255, unique=True)),
                ('url', models.URLField(help_text="URL de l'asset sur Cloudinary", max_length=1024)),
                ('asset_type', models.CharField(help_text="Type d'asset (image, video, raw, etc.)", max_length=50)),
                ('file_name', models.CharField(blank=True, help_text='Nom original du fichier', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cloudinary Asset',
                'verbose_name_plural': 'Cloudinary Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
