# Generated by Django 5.1.2 on 2025-12-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0006_cloudinaryasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudinaryasset',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Cloudinary Asset ID (unique, non-editable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cloudinaryasset',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True),
        ),
        migrations.AddField(
            model_name='cloudinaryasset',
            name='format',
            field=models.CharField(blank=True, help_text='Format du fichier (ex: glb, png)', max_length=50),
        ),
        migrations.AddField(
            model_name='cloudinaryasset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles de Cloudinary'),
        ),
        migrations.AddField(
            model_name='cloudinaryasset',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags associés à l'asset"),
        ),
    ]
