# Generated by Django 5.1.2 on 2025-12-10 00:46

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0007_cloudinaryasset_asset_id_cloudinaryasset_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometry',
            name='model_url',
        ),
        migrations.AddField(
            model_name='geometry',
            name='asset',
            field=models.ForeignKey(blank=True, help_text="Lien vers l'asset Cloudinary correspondant", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base_threlte_dv.cloudinaryasset'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='model_file',
            field=models.FileField(blank=True, help_text='Fichier 3D local (.glb, .gltf)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='models/'),
        ),
    ]
