# Generated by Django 4.1.7 on 2025-12-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base_threlte_dv", "0008_remove_geometry_model_url_geometry_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geometry",
            name="model_url",
            field=models.URLField(max_length=1024, blank=True, null=True),
        ),
    ]
