# Generated by Django 5.1.2 on 2025-12-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0008_remove_geometry_model_url_geometry_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometry',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='model_file',
        ),
        migrations.AddField(
            model_name='geometry',
            name='model_url',
            field=models.URLField(blank=True, help_text='URL du modèle 3D sur Cloudinary', max_length=1024, null=True),
        ),
    ]
