# Generated by Django 5.1.2 on 2025-12-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0008_remove_geometry_model_url_geometry_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometry',
            name='asset',
        ),
        migrations.AddField(
            model_name='geometry',
            name='cloudinary_asset',
            field=models.ForeignKey(blank=True, help_text="Lien vers l'asset Cloudinary correspondant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometries', to='Base_threlte_dv.cloudinaryasset'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='model_file',
            field=models.FileField(blank=True, help_text='Fichier 3D local (.glb, .gltf)', null=True, upload_to='models/'),
        ),
        migrations.CreateModel(
            name='B2Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2_file_id', models.CharField(help_text='ID unique du fichier sur B2', max_length=255, unique=True)),
                ('file_name', models.CharField(help_text='Nom du fichier sur B2 (inclut le chemin)', max_length=255)),
                ('original_name', models.CharField(blank=True, help_text='Nom original du fichier', max_length=255, null=True)),
                ('url', models.URLField(help_text="URL publique d'accès au fichier sur B2", max_length=1024)),
                ('bucket_name', models.CharField(help_text='Nom du bucket B2', max_length=255)),
                ('content_type', models.CharField(blank=True, help_text='Type MIME du fichier', max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 ou MD5 du fichier', max_length=64)),
                ('upload_timestamp', models.DateTimeField(blank=True, help_text="Timestamp d'upload B2", null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags associés à l'asset")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'B2 Asset',
                'verbose_name_plural': 'B2 Assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_name'], name='Base_threlt_file_na_309077_idx'), models.Index(fields=['bucket_name'], name='Base_threlt_bucket__47435a_idx'), models.Index(fields=['content_type'], name='Base_threlt_content_fd2d4d_idx')],
            },
        ),
        migrations.AddField(
            model_name='geometry',
            name='b2_asset',
            field=models.ForeignKey(blank=True, help_text="Lien vers l'asset B2 correspondant", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometries', to='Base_threlte_dv.b2asset'),
        ),
    ]
