# Generated by Django 5.1.2 on 2025-12-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0009_add_model_url_field'),
        ('Base_threlte_dv', '0009_remove_geometry_asset_remove_geometry_model_file_and_more'),
    ]

    operations = [
    ]
