# Generated by Django 5.1.2 on 2025-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0010_merge_20251211_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='visible',
            field=models.BooleanField(default=True, help_text="Activer/Désactiver l'affichage de la géométrie"),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='model_url',
            field=models.URLField(blank=True, help_text='URL du modèle 3D sur Cloudinary', max_length=1024, null=True),
        ),
    ]
