# Generated by Django 5.1.2 on 2025-12-17 16:40

import backend.Base_threlte_dv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0011_add_visible_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometry',
            name='scale',
            field=models.JSONField(default=backend.Base_threlte_dv.models.get_default_scale),
        ),
    ]
