# Generated by Django 5.1.2 on 2025-12-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_threlte_dv', '0011_geometry_scale_geometry_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='model_type',
            field=models.CharField(blank=True, choices=[('gltf', 'glTF'), ('glb', 'GLB'), ('jpg', 'JPEG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP')], help_text='Format du fichier (3D ou Image)', max_length=10),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='type',
            field=models.CharField(choices=[('box', 'Box'), ('torus', 'Torus'), ('icosahedron', 'Icosahedron'), ('nissangame', 'Nissan Game'), ('bibigame', 'Bibi Game'), ('garden', 'Garden'), ('bibi', 'Bibi'), ('vague', 'Vague'), ('sphere', 'Sphere'), ('nissan', 'Nissan'), ('tissus', 'Tissus'), ('desk', 'Desk'), ('gltf_model', 'GLTF Model'), ('text', 'Text'), ('text_scene', 'Text Scene'), ('image_plane', 'Image Plane')], default='box', max_length=20),
        ),
    ]
