<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/DcYcU.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
	import { getWorkingAssetUrl } from '$lib/utils/assetFallback';
	import { createDracoLoader } from '$lib/utils/draco-loader';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';

	let { ref = $bindable(new Group()), ...restProps } = $props();

	let gltfDcYcUModel = $state(null);

	onMount(async () => {
		if (browser) {
			try {
				const resolved = await getWorkingAssetUrl('DcYcU.glb', 'models');
				const loader = new GLTFLoader();
				loader.setDRACOLoader(createDracoLoader());
				gltfDcYcUModel = await loader.loadAsync(resolved);
			} catch (e) {
				console.error('Failed to load DcYcU model', e);
			}
		}
	});
</script>

<T is={ref} dispose={false} {...restProps}>
	{#if gltfDcYcUModel}
		<T.PointLight
			intensity={54351.41}
			decay={2}
			position={[4.08, 5.9, -1.01]}
			rotation={[-1.84, 0.6, 1.93]}
		/>
		<T.Mesh
			geometry={gltfDcYcUModel.nodes.Cube.geometry}
			material={gltfDcYcUModel.materials.Material}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[-1, -2.68, -1]}
		/>
		<T.Mesh
			geometry={gltfDcYcUModel.nodes.Cube001.geometry}
			material={gltfDcYcUModel.materials.Material}
			position={[0, 2.48, -2.88]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[-1, -2.68, -1]}
		/>
		<T.Mesh
			geometry={gltfDcYcUModel.nodes.Sphère.geometry}
			material={gltfDcYcUModel.materials.Matériau}
			position={[4.13, 0, 0]}
		/>
	{/if}

	<slot {ref} />
</T>
