<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/ghost.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
	import { getWorkingAssetUrl } from '$lib/utils/assetFallback';
	import { createDracoLoader } from '$lib/utils/draco-loader';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';

	let { ref = $bindable(new Group()), ...rest } = $props();

	let gltfGhostValue = $state(null);

	onMount(async () => {
		if (browser) {
			try {
				const resolved = await getWorkingAssetUrl('ghost.glb', 'models');
				const loader = new GLTFLoader();
				loader.setDRACOLoader(createDracoLoader());
				gltfGhostValue = await loader.loadAsync(resolved);
			} catch (e) {
				console.error('Failed to load Ghost model', e);
			}
		}
	});
</script>

<T is={ref} dispose={false} {...rest}>
	{#if gltfGhostValue}
		<T.Mesh
			geometry={gltfGhostValue.nodes.Ghost002.geometry}
			material={gltfGhostValue.materials.Outline}
		/>
	{/if}

	<slot {ref} />
</T>
