<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/ghost.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
	import { Group } from 'three';
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { getCloudinaryAssetUrl } from '$lib/utils/cloudinaryAssets';

	import { onMount } from 'svelte';

	export const ref = new Group();
	let { ...rest } = $props();

	let gltf = $state(null);

	onMount(() => {
		useGltf(getCloudinaryAssetUrl('/models/ghost.glb'))
			.then((model) => {
				gltf = model;
			})
			.catch((err) => {
				console.error('Failed to load Ghost model', err);
			});
	});
</script>

<T is={ref} dispose={false} {...rest}>
	{#if gltf}
		<T.Mesh geometry={gltf.nodes.Ghost002.geometry} material={gltf.materials.Outline} />
	{/if}

	<slot {ref} />

	<slot {ref} />
</T>
