<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ubt/DpDIST/Web_site_3D_anime_By_DV/static/models/ghost.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { getCloudinaryAssetUrl, configureDracoLoader } from '$lib/utils/cloudinaryAssets';
	import { onMount } from 'svelte';

	export const ref = new Group();
	let gltf;
	let component;

	onMount(() => {
		configureDracoLoader();
		gltf = useGltf(getCloudinaryAssetUrl('/models/ghost.glb'));
		component = forwardEventHandlers();
	});
</script>

<T is={ref} dispose={false} {...restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Ghost002.geometry} material={gltf.materials.Outline} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
