<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\Utente\Desktop\Trasferimento-PC\Projects\Youtube\Threlte\spaceship-header\static\models\threlte.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { getCloudinaryAssetUrl, 
	import { onMount } from 'svelte';

	export const ref = new Group();
	let gltf;
	let component;

	onMount(() => {
		
		gltf = useGltf(getCloudinaryAssetUrl('/models/threlte.glb'));
		component = forwardEventHandlers();
	});
</script>

<T is={ref} dispose={false} {...restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cube.geometry}
			material={gltf.materials.Material}
			position={[0, 1, 2]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
