# Generated by Django 5.1.2 on 2025-12-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_remove_film_image_film_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-id']},
        ),
    ]
